chore: remove separate stage dbcs mapping
Health-Education-England/TIS-REFERENCE pull request #313
Opened 2023-12-07 13:57 UTC by jayanta2018

GMC kindly changed the new DBCs to their stage. So we don't need those changes anymore in our reference service.

TIS21-4657

2023-12-07 14:49 UTC, hihilary requested changes

2023-12-07 15:09 UTC, hihilary commented
Do you mind fixing the code smell please?

2023-12-08 10:56 UTC, jayanta2018 commented
> Do you mind fixing the code smell please?

It is fixed now. Thanks

2023-12-08 11:38 UTC, hihilary approved these changes

2023-12-08 11:38 UTC, merged